name: Manage releases

on:
  push:
    branches: main

concurrency: ${{ github.workflow }} (${{ github.ref }})

jobs:
  manage:
    name: Manage releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Wait for formatting checks
        uses: johannesvedder/await-workflow@v1
        with:
          workflowId: check-formatting.yml
          retryIntervalSeconds: 5
          initialWaitSeconds: 5

      - name: Wait for linting checks
        uses: johannesvedder/await-workflow@v1
        with:
          workflowId: check-linting.yml
          retryIntervalSeconds: 5
          initialWaitSeconds: 5

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup pnpm (version 8)
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js (version 20)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      # - name: Add authentication token
      #   run: |
      #     cat << EOF > $HOME/.npmrc
      #       //npm.pkg.github.com/:_authToken=${{ github.token }}
      #     EOF

      - name: Install dependencies
        run: pnpm install

      - name: Create pull request (or release)
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          commit: Add new releases
          title: Pending releases
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          (git commit -m "Build release" && git push) || echo "No changes found, not pushing"
